import builtins
from collections.abc import Callable
from datetime import datetime
from typing import Protocol, Self

from app.domain.entities import Category, PomodoroSettings, SessionSource, StudySession, Timer


class CategoryRepository(Protocol):
    def list(self, *, include_deleted: bool = False) -> list[Category]: ...

    def get(self, category_id: str, *, include_deleted: bool = False) -> Category | None: ...

    def add(self, category: Category) -> None: ...

    def save(self, category: Category) -> None: ...


class PomodoroSettingsRepository(Protocol):
    def get(self) -> PomodoroSettings | None: ...

    def add(self, settings: PomodoroSettings) -> None: ...

    def save(self, settings: PomodoroSettings) -> None: ...


class TimerRepository(Protocol):
    def get(self, timer_id: str) -> Timer | None: ...

    def get_active(self) -> Timer | None: ...

    def list_by_study_flow_session_id(self, session_id: str) -> list[Timer]: ...

    def add(self, timer: Timer) -> None: ...

    def save(self, timer: Timer) -> None: ...


class StudySessionRepository(Protocol):
    def list(self, *, include_deleted: bool = False) -> builtins.list[StudySession]: ...

    def list_recent(self, *, limit: int) -> builtins.list[StudySession]: ...

    def list_completed_between(
        self, start: datetime, end: datetime
    ) -> builtins.list[StudySession]: ...

    def get(self, session_id: str, *, include_deleted: bool = False) -> StudySession | None: ...

    def get_by_timer_id(self, timer_id: str) -> StudySession | None: ...

    def get_active_by_source(self, source: SessionSource) -> StudySession | None: ...

    def add(self, study_session: StudySession) -> None: ...

    def save(self, study_session: StudySession) -> None: ...


class UnitOfWork(Protocol):
    categories: CategoryRepository
    pomodoro_settings: PomodoroSettingsRepository
    timers: TimerRepository
    sessions: StudySessionRepository

    def __enter__(self) -> Self: ...

    def __exit__(self, exc_type: object, exc_value: object, traceback: object) -> None: ...

    def commit(self) -> None: ...

    def flush(self) -> None: ...

    def rollback(self) -> None: ...


type UnitOfWorkFactory = Callable[[], UnitOfWork]
